server.port=8081
application.url=https://www.google.com
screenshot.path=C:\\screenshots
browser=chrome

//spring.profiles.active=testing
//spring.profiles.active=staging
spring.profiles.active=production